spring:
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.128:8848
#      config:
#        server-addr: 192.168.200.129:8848
  profiles:
    active: dev