#server:
#  port: 8206
#mybatis-plus:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.121.128:3306/gmall_product?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#    hikari:
#      connection-test-query: SELECT 1 # 自动检测连接
#      connection-timeout: 60000 #数据库连接超时时间,默认30秒
#      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
#      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#      maximum-pool-size: 12 #连接池最大连接数，默认是10
#      minimum-idle: 10 #最小空闲连接数量
#      pool-name: SPHHikariPool # 连接池名称
#  redis:
#    host: 192.168.121.128
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        max-active: 20 #最大连接数
#        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
#        max-idle: 5    #最大空闲
#        min-idle: 0     #最小空闲
#  cloud:
#    sentinel:
#      transport:
#        dashboard: http://192.168.121.128:8858
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#minio:
#  endpointUrl: http://192.168.121.128:9000
#  accessKey: admin
#  secreKey: admin123456
#  bucketName: gmall
## rabbitmq 暂时不用配置！
## com.zaxxer.hikari.HikariDataSource spring boot 高版本的时候才会出现！ 号称：java web层门链接最快的！